/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

fn sum_even_fib(max: u32) -> u32 {
  let mut sum = 0;
  let mut prev = 1;
  let mut curr = 1;
  while curr < max {
    curr = curr + prev;
    prev = curr - prev;
    if curr % 2 == 0 && curr < max {
      sum += curr;
    }
  }
  return sum;
}

fn main() {
  let total = sum_even_fib(4000000);
  println!("Total is: {}", total);
}

